---
title: Homelab.lt
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: admin@homelab.lt
description: Personal exploration while developing and administering IT systems, profesionaly
  and just for fun.
baseurl: ''
url: ''
theme: minima
plugins:
- jekyll-feed
jekyll_admin:
  homepage: posts
markdown: kramdown
highlighter: rouge
